/**
 * src/constants/permissions.js
 * Centralized permissions and roles dictionary for RBAC and PBAC throughout the application.
 */

export const ROLES = Object.freeze({
  ADMIN: "ADMIN",
  ADMINISTRATOR: "ADMINISTRATOR",
  SUPER_ADMIN: "SUPER_ADMIN",
  MANAGER: "MANAGER",
  LOAN_OFFICER: "LOAN_OFFICER",
  COLLECTION_AGENT: "COLLECTION_AGENT",
  ACCOUNTANT: "ACCOUNTANT",
  USER: "USER",
});

export const PERMISSIONS = Object.freeze({
  // Dashboard & Analytics
  DASHBOARD_VIEW: "DASHBOARD_VIEW",
  ANALYTICS_VIEW: "ANALYTICS_VIEW",

  // Customers
  CUSTOMER_VIEW: "CUSTOMER_VIEW",
  CUSTOMER_CREATE: "CUSTOMER_CREATE",
  CUSTOMER_EDIT: "CUSTOMER_EDIT",
  CUSTOMER_DELETE: "CUSTOMER_DELETE",
  CUSTOMER_DOCUMENTS_VIEW: "CUSTOMER_DOCUMENTS_VIEW",
  GUARANTORS_VIEW: "GUARANTORS_VIEW",

  // Loan Plans
  LOAN_PLAN_VIEW: "LOAN_PLAN_VIEW",
  LOAN_PLAN_CREATE: "LOAN_PLAN_CREATE",
  LOAN_PLAN_EDIT: "LOAN_PLAN_EDIT",
  LOAN_PLAN_DELETE: "LOAN_PLAN_DELETE",

  // Interest-Only Loan Plans
  INTEREST_LOAN_PLAN_VIEW: "INTEREST_LOAN_PLAN_VIEW",
  INTEREST_LOAN_PLAN_CREATE: "INTEREST_LOAN_PLAN_CREATE",
  INTEREST_LOAN_PLAN_EDIT: "INTEREST_LOAN_PLAN_EDIT",
  INTEREST_LOAN_PLAN_DELETE: "INTEREST_LOAN_PLAN_DELETE",

  // Interest-Only Loans (Customer Interest)
  INTEREST_ONLY_LOAN_VIEW: "INTEREST_ONLY_LOAN_VIEW",
  INTEREST_ONLY_LOAN_CREATE: "INTEREST_ONLY_LOAN_CREATE",
  INTEREST_ONLY_LOAN_EDIT: "INTEREST_ONLY_LOAN_EDIT",
  INTEREST_ONLY_LOAN_DELETE: "INTEREST_ONLY_LOAN_DELETE",
  INTEREST_ONLY_PAYMENT_CREATE: "INTEREST_ONLY_PAYMENT_CREATE",
  INTEREST_ONLY_PAYMENT_DELETE: "INTEREST_ONLY_PAYMENT_DELETE",
  INTEREST_COLLECTION_VIEW: "INTEREST_COLLECTION_VIEW",
  INTEREST_COLLECTION_CREATE: "INTEREST_COLLECTION_CREATE",

  // Loan Applications & Loans
  LOAN_APPLICATION_VIEW: "LOAN_APPLICATION_VIEW",
  LOAN_APPLICATION_CREATE: "LOAN_APPLICATION_CREATE",
  LOAN_APPLICATION_EDIT: "LOAN_APPLICATION_EDIT",
  LOAN_APPLICATION_DELETE: "LOAN_APPLICATION_DELETE",
  LOAN_VIEW: "LOAN_VIEW",
  LOAN_CREATE: "LOAN_CREATE",
  LOAN_EDIT: "LOAN_EDIT",
  LOAN_DELETE: "LOAN_DELETE",
  LOAN_APPROVAL_VIEW: "LOAN_APPROVAL_VIEW",
  LOAN_APPROVAL_ACTION: "LOAN_APPROVAL_ACTION",

  // Hand Loans & Personal Chits
  HAND_LOAN_VIEW: "HAND_LOAN_VIEW",
  HAND_LOAN_CREATE: "HAND_LOAN_CREATE",
  HAND_LOAN_EDIT: "HAND_LOAN_EDIT",
  HAND_LOAN_DELETE: "HAND_LOAN_DELETE",
  PERSONAL_CHIT_VIEW: "PERSONAL_CHIT_VIEW",
  PERSONAL_CHIT_CREATE: "PERSONAL_CHIT_CREATE",
  PERSONAL_CHIT_EDIT: "PERSONAL_CHIT_EDIT",
  PERSONAL_CHIT_DELETE: "PERSONAL_CHIT_DELETE",

  // Collections & Due Collections
  LOAN_COLLECTION_VIEW: "LOAN_COLLECTION_VIEW",
  LOAN_COLLECTION_CREATE: "LOAN_COLLECTION_CREATE",
  LOAN_COLLECTION_EDIT: "LOAN_COLLECTION_EDIT",
  LOAN_COLLECTION_DELETE: "LOAN_COLLECTION_DELETE",
  DUE_COLLECTION_VIEW: "DUE_COLLECTION_VIEW",
  DUE_COLLECTION_CREATE: "DUE_COLLECTION_CREATE",
  DUE_COLLECTION_EDIT: "DUE_COLLECTION_EDIT",
  COLLECTION_VIEW: "COLLECTION_VIEW",
  COLLECTION_CREATE: "COLLECTION_CREATE",

  // Organization & Banking
  COMPANY_VIEW: "COMPANY_VIEW",
  COMPANY_EDIT: "COMPANY_EDIT",
  BANK_ACCOUNT_VIEW: "BANK_ACCOUNT_VIEW",
  BANK_ACCOUNT_CREATE: "BANK_ACCOUNT_CREATE",
  BANK_ACCOUNT_EDIT: "BANK_ACCOUNT_EDIT",
  BANK_ACCOUNT_DELETE: "BANK_ACCOUNT_DELETE",
  BANK_TRANSACTION_VIEW: "BANK_TRANSACTION_VIEW",
  BANK_TRANSACTION_CREATE: "BANK_TRANSACTION_CREATE",
  BANK_TRANSACTION_DELETE: "BANK_TRANSACTION_DELETE",

  // Assets & Categories
  ASSET_CATEGORY_VIEW: "ASSET_CATEGORY_VIEW",
  ASSET_CATEGORY_CREATE: "ASSET_CATEGORY_CREATE",
  ASSET_CATEGORY_EDIT: "ASSET_CATEGORY_EDIT",
  ASSET_CATEGORY_DELETE: "ASSET_CATEGORY_DELETE",
  ASSET_VIEW: "ASSET_VIEW",
  ASSET_CREATE: "ASSET_CREATE",
  ASSET_EDIT: "ASSET_EDIT",
  ASSET_DELETE: "ASSET_DELETE",

  // Roles & Users Administration
  USER_VIEW: "USER_VIEW",
  USER_CREATE: "USER_CREATE",
  USER_EDIT: "USER_EDIT",
  USER_DELETE: "USER_DELETE",
  ROLE_VIEW: "ROLE_VIEW",
  ROLE_CREATE: "ROLE_CREATE",
  ROLE_EDIT: "ROLE_EDIT",
  ROLE_DELETE: "ROLE_DELETE",
  ROLE_PERMISSION_VIEW: "ROLE_PERMISSION_VIEW",
  ROLE_PERMISSION_EDIT: "ROLE_PERMISSION_EDIT",
  USER_PERMISSION_VIEW: "USER_PERMISSION_VIEW",
  USER_PERMISSION_EDIT: "USER_PERMISSION_EDIT",

  // Reports
  LOAN_REPORT_VIEW: "LOAN_REPORT_VIEW",
  LOAN_INSTALLMENT_REPORT_VIEW: "LOAN_INSTALLMENT_REPORT_VIEW",
  COLLECTION_REPORT_VIEW: "COLLECTION_REPORT_VIEW",
  INTEREST_COLLECTION_REPORT_VIEW: "INTEREST_COLLECTION_REPORT_VIEW",
  CUSTOMER_REPORT_VIEW: "CUSTOMER_REPORT_VIEW",

  // Settings
  SETTINGS_VIEW: "SETTINGS_VIEW",
  SETTINGS_EDIT: "SETTINGS_EDIT",
});

// UI Helper array for dropdowns or legacy references
export const AVAILABLE_PERMISSIONS = Object.entries(PERMISSIONS).map(
  ([key, value]) => ({
    key: value,
    label: key
      .toLowerCase()
      .split("_")
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join(" "),
  })
);
