import React, { useState, useEffect } from "react";
import { X, Loader2, Percent, Layers, Lock } from "lucide-react";
import {
  INTEREST_TYPE_OPTIONS,
  INTEREST_TYPE_LABELS,
  INTEREST_FREQUENCY_OPTIONS,
  INTEREST_FREQUENCY_LABELS,
  CALCULATION_METHOD_OPTIONS,
  CALCULATION_METHOD_LABELS,
  PRINCIPAL_BASIS_OPTIONS,
  PRINCIPAL_BASIS_LABELS,
  PAYMENT_TYPE_OPTIONS,
  PAYMENT_TYPE_LABELS,
  STATUS_OPTIONS,
} from "../utils/interestPlanHelpers.js";

const emptyForm = {
  plan_name: "",
  interest_type: "percentage",
  interest_value: "",
  interest_frequency: "monthly",
  calculation_method: "simple",
  principal_basis: "outstanding_principal",
  payment_type: "anytime",
  description: "",
  status: "active",
};

/**
 * InterestPlanFormModal
 * Modal for creating and editing anytime interest loan plans.
 * Plan code is strictly auto-generated by the backend with meaningful formatting.
 * In edit mode, core financial terms are locked to maintain accounting consistency.
 */
export default function InterestPlanFormModal({
  open,
  initialData,
  loading,
  error,
  onClose,
  onSubmit,
}) {
  const isEdit = Boolean(initialData?.id);
  const [form, setForm] = useState(emptyForm);
  const [fieldErrors, setFieldErrors] = useState({});

  useEffect(() => {
    if (!open) return;
    if (isEdit) {
      setForm({
        plan_name: initialData.plan_name || "",
        interest_type: initialData.interest_type || "percentage",
        interest_value:
          initialData.interest_value != null && initialData.interest_value !== ""
            ? parseFloat(initialData.interest_value)
            : "",
        interest_frequency: initialData.interest_frequency || "monthly",
        calculation_method: initialData.calculation_method || "simple",
        principal_basis: initialData.principal_basis || "outstanding_principal",
        payment_type: initialData.payment_type || "anytime",
        description: initialData.description || "",
        status: initialData.status || "active",
      });
    } else {
      setForm(emptyForm);
    }
    setFieldErrors({});
  }, [open, initialData, isEdit]);

  if (!open) return null;

  const handleChange = (field) => (e) => {
    setForm((prev) => ({ ...prev, [field]: e.target.value }));
    setFieldErrors((prev) => ({ ...prev, [field]: null }));
  };

  const validate = () => {
    const errors = {};
    if (!form.plan_name.trim()) {
      errors.plan_name = "Plan name is required";
    }

    if (form.interest_value === "" || form.interest_value === null) {
      errors.interest_value = "Interest value is required";
    } else if (Number(form.interest_value) < 0) {
      errors.interest_value = "Interest value cannot be negative";
    }

    setFieldErrors(errors);
    return Object.keys(errors).length === 0;
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!validate()) return;

    const payload = {
      plan_name: form.plan_name.trim(),
      interest_type: form.interest_type,
      interest_value: Number(form.interest_value),
      interest_frequency: form.interest_frequency,
      calculation_method: form.calculation_method,
      principal_basis: form.principal_basis,
      payment_type: form.payment_type,
      status: form.status,
      description: form.description?.trim() || null,
    };

    onSubmit(payload);
  };

  return (
    <div className="modal modal-open z-50">
      <div className="modal-box max-w-2xl p-0 overflow-hidden shadow-2xl rounded-2xl border border-base-300">
        {/* Modal Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-base-200 bg-base-100">
          <div className="flex items-center gap-2.5">
            <span className="flex items-center justify-center w-9 h-9 rounded-xl bg-primary/10 text-primary">
              <Percent size={18} />
            </span>
            <div>
              <h3 className="font-semibold text-base text-base-content">
                {isEdit ? "Edit Interest Plan" : "Create Interest Plan"}
              </h3>
              <p className="text-xs text-base-content/50">
                {isEdit
                  ? `Editing configuration for ${initialData?.plan_code || "plan"}`
                  : "Configure rates and terms for flexible anytime interest loans"}
              </p>
            </div>
          </div>
          <button
            type="button"
            className="btn btn-ghost btn-circle btn-sm text-base-content/50 hover:text-base-content"
            onClick={onClose}
            disabled={loading}
          >
            <X size={16} />
          </button>
        </div>

        {/* Global Error Alert */}
        {error && (
          <div className="mx-6 mt-4 p-3 rounded-xl bg-error/10 border border-error/20 text-error text-xs flex items-center gap-2">
            <span>
              {typeof error === "string"
                ? error
                : error?.message || "Failed to save plan. Please check inputs."}
            </span>
          </div>
        )}

        {/* Edit Mode Information Banner */}
        {isEdit && (
          <div className="mx-6 mt-4 p-3.5 rounded-xl bg-amber-500/10 border border-amber-500/25 text-amber-900 dark:text-amber-200 text-xs flex items-start gap-2.5">
            <Lock size={15} className="text-amber-600 dark:text-amber-400 shrink-0 mt-0.5" />
            <div>
              <p className="font-bold">Core Financial Parameters Locked</p>
              <p className="opacity-90 mt-0.5 leading-relaxed">
                Interest configuration and plan code are fixed for existing plans to preserve auditing integrity. You can update the <strong>Plan Name</strong>, <strong>Status</strong>, and <strong>Description / Remarks</strong>.
              </p>
            </div>
          </div>
        )}

        {/* Form Body */}
        <form onSubmit={handleSubmit} className="px-6 py-4 space-y-4 max-h-[75vh] overflow-y-auto">
          {/* Section 1: Basic Information */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 items-start">
            {/* Plan Name */}
            <div className="form-control">
              <label className="label py-1">
                <span className="label-text text-xs font-semibold">
                  Plan Name <span className="text-error">*</span>
                </span>
              </label>
              <input
                type="text"
                placeholder="e.g. Standard Monthly 2%"
                className={`input input-bordered input-sm w-full rounded-lg text-xs ${
                  fieldErrors.plan_name ? "input-error" : ""
                }`}
                value={form.plan_name}
                onChange={handleChange("plan_name")}
              />
              {fieldErrors.plan_name && (
                <span className="text-error text-[11px] mt-1">
                  {fieldErrors.plan_name}
                </span>
              )}
            </div>

            {/* Plan Reference Code (Backend Auto-generated) */}
            <div className="form-control">
              <label className="label py-1">
                <span className="label-text text-xs font-semibold text-base-content/70">
                  Plan Reference Code
                </span>
              </label>
              {isEdit ? (
                <div className="flex items-center h-8 px-3 rounded-lg border border-base-300 bg-base-200/60 text-xs font-mono font-bold text-primary gap-2">
                  <Lock size={12} className="opacity-60" />
                  {initialData?.plan_code || "—"}
                  <span className="badge badge-xs badge-ghost text-[10px] ml-auto font-sans font-normal opacity-60">
                    Assigned
                  </span>
                </div>
              ) : (
                <div className="flex items-center h-8 px-3 rounded-lg border border-dashed border-base-300 bg-base-200/30 text-xs text-base-content/50 font-mono gap-1.5">
                  <span className="w-1.5 h-1.5 rounded-full bg-success/60 animate-pulse" />
                  <span>Auto-generated by backend (e.g. INT-MONTHLY-2PCT)</span>
                </div>
              )}
            </div>
          </div>

          {/* Section 2: Rate & Frequency */}
          <div className="p-4 rounded-xl bg-base-200/50 border border-base-300 space-y-4">
            <div className="flex items-center justify-between">
              <h4 className="text-xs font-semibold uppercase tracking-wider text-base-content/70 flex items-center gap-1.5">
                <Layers size={14} className="text-primary" />
                Interest Configuration
              </h4>
              {isEdit && (
                <span className="badge badge-sm badge-ghost text-[10px] font-medium gap-1 text-base-content/60">
                  <Lock size={10} /> Locked in Edit Mode
                </span>
              )}
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              {/* Interest Type */}
              <div className="form-control">
                <label className="label py-1">
                  <span className="label-text text-xs font-medium">Interest Type</span>
                </label>
                <select
                  disabled={isEdit}
                  className={`select select-bordered select-sm w-full rounded-lg text-xs ${
                    isEdit ? "bg-base-200 cursor-not-allowed opacity-70" : ""
                  }`}
                  value={form.interest_type}
                  onChange={handleChange("interest_type")}
                >
                  {INTEREST_TYPE_OPTIONS.map((opt) => (
                    <option key={opt} value={opt}>
                      {INTEREST_TYPE_LABELS[opt] || opt}
                    </option>
                  ))}
                </select>
              </div>

              {/* Interest Value */}
              <div className="form-control">
                <label className="label py-1">
                  <span className="label-text text-xs font-medium">
                    Rate / Amount <span className="text-error">*</span>
                  </span>
                </label>
                <div className="relative">
                  <input
                    type="number"
                    step="any"
                    min="0"
                    disabled={isEdit}
                    placeholder={
                      form.interest_type === "percentage" ? "e.g. 2" : "e.g. 1000"
                    }
                    className={`input input-bordered input-sm w-full pr-8 rounded-lg text-xs ${
                      fieldErrors.interest_value ? "input-error" : ""
                    } ${isEdit ? "bg-base-200 cursor-not-allowed opacity-70" : ""}`}
                    value={form.interest_value}
                    onChange={handleChange("interest_value")}
                  />
                  <span className="absolute right-2.5 top-1/2 -translate-y-1/2 text-base-content/40 text-xs">
                    {form.interest_type === "percentage" ? "%" : "₹"}
                  </span>
                </div>
                {fieldErrors.interest_value && (
                  <span className="text-error text-[11px] mt-1">
                    {fieldErrors.interest_value}
                  </span>
                )}
              </div>

              {/* Interest Frequency */}
              <div className="form-control">
                <label className="label py-1">
                  <span className="label-text text-xs font-medium">Billing Frequency</span>
                </label>
                <select
                  disabled={isEdit}
                  className={`select select-bordered select-sm w-full rounded-lg text-xs ${
                    isEdit ? "bg-base-200 cursor-not-allowed opacity-70" : ""
                  }`}
                  value={form.interest_frequency}
                  onChange={handleChange("interest_frequency")}
                >
                  {INTEREST_FREQUENCY_OPTIONS.map((opt) => (
                    <option key={opt} value={opt}>
                      {INTEREST_FREQUENCY_LABELS[opt] || opt}
                    </option>
                  ))}
                </select>
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              {/* Principal Basis */}
              <div className="form-control">
                <label className="label py-1">
                  <span className="label-text text-xs font-medium">Principal Basis</span>
                </label>
                <select
                  disabled={isEdit}
                  className={`select select-bordered select-sm w-full rounded-lg text-xs ${
                    isEdit ? "bg-base-200 cursor-not-allowed opacity-70" : ""
                  }`}
                  value={form.principal_basis}
                  onChange={handleChange("principal_basis")}
                >
                  {PRINCIPAL_BASIS_OPTIONS.map((opt) => (
                    <option key={opt} value={opt}>
                      {PRINCIPAL_BASIS_LABELS[opt] || opt}
                    </option>
                  ))}
                </select>
              </div>

              {/* Calculation Method (Standardized to Simple Interest) */}
              <div className="form-control">
                <label className="label py-1">
                  <span className="label-text text-xs font-medium">Calculation Method</span>
                </label>
                <select
                  disabled
                  className="select select-bordered select-sm w-full rounded-lg text-xs bg-base-200 cursor-not-allowed opacity-70"
                  value={form.calculation_method}
                  onChange={handleChange("calculation_method")}
                >
                  {CALCULATION_METHOD_OPTIONS.map((opt) => (
                    <option key={opt} value={opt}>
                      {CALCULATION_METHOD_LABELS[opt] || opt}
                    </option>
                  ))}
                </select>
              </div>

              {/* Payment Type (Standardized to Anytime Repayment) */}
              <div className="form-control">
                <label className="label py-1">
                  <span className="label-text text-xs font-medium">Payment Type</span>
                </label>
                <select
                  disabled
                  className="select select-bordered select-sm w-full rounded-lg text-xs bg-base-200 cursor-not-allowed opacity-70"
                  value={form.payment_type}
                  onChange={handleChange("payment_type")}
                >
                  {PAYMENT_TYPE_OPTIONS.map((opt) => (
                    <option key={opt} value={opt}>
                      {PAYMENT_TYPE_LABELS[opt] || opt}
                    </option>
                  ))}
                </select>
              </div>
            </div>
          </div>

          {/* Section 3: Status & Description */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            {/* Status */}
            <div className="form-control sm:col-span-1">
              <label className="label py-1">
                <span className="label-text text-xs font-medium">Status</span>
              </label>
              <select
                className="select select-bordered select-sm w-full rounded-lg text-xs"
                value={form.status}
                onChange={handleChange("status")}
              >
                {STATUS_OPTIONS.map((opt) => (
                  <option key={opt} value={opt}>
                    {opt.charAt(0).toUpperCase() + opt.slice(1)}
                  </option>
                ))}
              </select>
            </div>

            {/* Description */}
            <div className="form-control sm:col-span-2">
              <label className="label py-1">
                <span className="label-text text-xs font-medium">Description / Remarks</span>
              </label>
              <textarea
                rows={2}
                placeholder="Optional notes or operational details regarding this plan"
                className="textarea textarea-bordered textarea-sm w-full rounded-lg text-xs"
                value={form.description}
                onChange={handleChange("description")}
              />
            </div>
          </div>

          {/* Modal Actions Footer */}
          <div className="modal-action border-t border-base-200 pt-4 mt-4 flex justify-end gap-2">
            <button
              type="button"
              className="btn btn-ghost btn-sm rounded-lg"
              onClick={onClose}
              disabled={loading}
            >
              Cancel
            </button>
            <button
              type="submit"
              className="btn btn-primary btn-sm rounded-lg gap-2"
              disabled={loading}
            >
              {loading && <Loader2 size={14} className="animate-spin" />}
              {isEdit ? "Save Changes" : "Create Plan"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
